const fs = require('fs');
let html = fs.readFileSync('admin.html', 'utf8');

// Replace the stub adeManageAreasModal with a full dedicated Areas manager
const OLD = [
'        // ── Manage Areas quick modal (admin header button) ──────────────────────',
'    async function adeManageAreasModal() {',
'        // Delegate to the full location modal if available',
'        if (typeof adeLandmarkModal === \'function\') { adeLandmarkModal(); return; }',
'    }'
].join('\r\n');

const NEW = [
'    // ── Manage Areas modal — dedicated, linked to Landmarks ─────────────────',
'    async function adeManageAreasModal() {',
'        var existing = document.getElementById(\'adeAreasMgrModal\');',
'        if (existing) existing.remove();',
'',
'        // Load fresh data',
'        var [rL, rA] = await Promise.all([fetch(\'/api/landmarks\'), fetch(\'/api/areas\')]);',
'        var [dL, dA] = await Promise.all([rL.json(), rA.json()]);',
'        var allLandmarks = dL.landmarks || [];',
'        var allAreas     = dA.areas     || [];',
'        _adeAllLandmarks = allLandmarks;',
'        _adeAllAreas     = allAreas;',
'',
'        var selLmId   = allLandmarks.length ? allLandmarks[0].id : null;',
'        var editingAr = null; // area id being inline-edited',
'',
'        var overlay = document.createElement(\'div\');',
'        overlay.id = \'adeAreasMgrModal\';',
'        overlay.style.cssText = \'display:flex;position:fixed;inset:0;background:rgba(0,0,0,.6);z-index:2100;align-items:flex-start;justify-content:center;padding-top:40px;overflow-y:auto;\';',
'',
'        function areasForLm() {',
'            return allAreas.filter(function(a) { return a.landmarkId === selLmId; });',
'        }',
'',
'        function render() {',
'            var lm    = allLandmarks.find(function(l) { return l.id === selLmId; });',
'            var areas = areasForLm();',
'            var lmName = lm ? lm.name : \'\';',
'',
'            var h = \'<div style="background:#fff;border-radius:16px;padding:28px;width:96%;max-width:820px;box-shadow:0 8px 40px rgba(0,0,0,.25);margin-bottom:40px;">\';',
'',
'            // ── Header ──────────────────────────────────────────────────────',
'            h += \'<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;border-bottom:2px solid #f0f0f0;padding-bottom:14px;">\';',
'            h += \'<div>\';',
'            h += \'<h3 style="margin:0 0 4px;font-size:1.15rem;color:#1a237e;"><i class="fas fa-map" style="color:#6A1B9A;margin-right:10px;"></i>Manage Areas</h3>\';',
'            h += \'<p style="margin:0;font-size:.75rem;color:#888;">Areas are linked to Landmarks. Select a Landmark to manage its Areas.</p>\';',
'            h += \'</div>\';',
'            h += \'<span onclick="document.getElementById(\\\'adeAreasMgrModal\\\').remove()" style="font-size:1.5rem;cursor:pointer;color:#999;line-height:1;">&times;</span>\';',
'            h += \'</div>\';',
'',
'            h += \'<div style="display:grid;grid-template-columns:240px 1fr;gap:20px;">\';',
'',
'            // ── Left col: Landmarks (selector) ──────────────────────────────',
'            h += \'<div style="border-right:2px solid #f0f0f0;padding-right:18px;display:flex;flex-direction:column;gap:8px;">\';',
'            h += \'<div style="font-size:.7rem;font-weight:800;text-transform:uppercase;letter-spacing:.07em;color:#E65100;margin-bottom:4px;"><i class="fas fa-map-marker-alt" style="margin-right:5px;"></i>Landmark</div>\';',
'            h += \'<div style="font-size:.73rem;color:#aaa;margin-bottom:6px;">Click a landmark to manage its areas</div>\';',
'            h += \'<div style="overflow-y:auto;display:flex;flex-direction:column;gap:6px;max-height:380px;">\';',
'            allLandmarks.forEach(function(l) {',
'                var isSel = l.id === selLmId;',
'                h += \'<div onclick="amArSelLm(this)" data-lid="\' + l.id + \'" style="display:flex;align-items:center;gap:8px;padding:10px 14px;background:\' + (isSel ? \'#FFF3E0\' : \'#f8f9fa\') + \';border:2px solid \' + (isSel ? \'#F59E0B\' : \'transparent\') + \';border-radius:8px;cursor:pointer;">\';',
'                h += \'<i class="fas fa-map-marker-alt" style="color:\' + (isSel ? \'#E65100\' : \'#ccc\') + \';font-size:.8rem;"></i>\';',
'                h += \'<span style="font-weight:\' + (isSel ? \'700\' : \'500\') + \';font-size:.85rem;color:\' + (isSel ? \'#E65100\' : \'#444\') + \';flex:1;">\' + l.name + \'</span>\';',
'                if (isSel) h += \'<i class="fas fa-chevron-right" style="color:#F59E0B;font-size:.7rem;"></i>\';',
'                h += \'</div>\';',
'            });',
'            if (!allLandmarks.length) h += \'<div style="color:#aaa;text-align:center;padding:20px;font-size:.82rem;">No landmarks yet.<br><a href="#" onclick="event.preventDefault();document.getElementById(\\\'adeAreasMgrModal\\\').remove();adeLandmarkModal();" style="color:#E65100;">Manage Landmarks</a></div>\';',
'            h += \'</div>\';', // end scroll
'            h += \'</div>\';', // end left col
'',
'            // ── Right col: Areas for selected Landmark ───────────────────────',
'            h += \'<div style="display:flex;flex-direction:column;gap:10px;">\';',
'',
'            if (!selLmId) {',
'                h += \'<div style="color:#aaa;text-align:center;padding:40px 20px;font-size:.85rem;"><i class="fas fa-hand-point-left" style="font-size:1.5rem;display:block;margin-bottom:8px;"></i>Select a Landmark on the left</div>\';',
'            } else {',
'                // Section header',
'                h += \'<div style="display:flex;align-items:center;gap:10px;padding-bottom:10px;border-bottom:2px solid #f0f0f0;">\';',
'                h += \'<i class="fas fa-map" style="color:#6A1B9A;"></i>\';',
'                h += \'<span style="font-size:.72rem;font-weight:800;text-transform:uppercase;letter-spacing:.07em;color:#6A1B9A;">Areas under \' + lmName + \'</span>\';',
'                h += \'<span style="margin-left:auto;font-size:.73rem;color:#888;">\' + areas.length + \' area(s)\' + \'</span>\';',
'                h += \'</div>\';',
'',
'                // Add new area row',
'                h += \'<div style="display:flex;gap:8px;align-items:center;">\';',
'                h += \'<input type="text" id="amArNewInput" class="form-control" placeholder="Type new area name and click Add..." style="flex:1;font-size:.85rem;">\';',
'                h += \'<button onclick="amArAddArea(this)" data-lmid="\' + selLmId + \'" style="padding:0 16px;height:38px;border:none;border-radius:8px;background:#6A1B9A;color:#fff;font-weight:700;cursor:pointer;white-space:nowrap;"><i class="fas fa-plus" style="margin-right:5px;"></i>Add</button>\';',
'                h += \'</div>\';',
'',
'                // Areas list',
'                h += \'<div style="overflow-y:auto;display:flex;flex-direction:column;gap:6px;max-height:300px;">\';',
'                if (!areas.length) {',
'                    h += \'<div style="color:#aaa;text-align:center;padding:24px;font-size:.83rem;border:2px dashed #e0e0e0;border-radius:10px;">No areas yet for \' + lmName + \'.<br>Type a name above and click Add.</div>\';',
'                } else {',
'                    areas.forEach(function(a) {',
'                        var isEditing = editingAr === a.id;',
'                        h += \'<div style="display:flex;align-items:center;gap:8px;padding:10px 14px;background:#f8f0ff;border:1.5px solid \' + (isEditing ? \'#6A1B9A\' : \'#EDE7F6\') + \';border-radius:8px;">\';',
'                        if (isEditing) {',
'                            h += \'<i class="fas fa-map" style="color:#6A1B9A;font-size:.8rem;"></i>\';',
'                            h += \'<input type="text" id="amArEditInput_\' + a.id + \'" value="\' + a.name.replace(/"/g,\'&quot;\') + \'" style="flex:1;font-size:.85rem;border:1.5px solid #6A1B9A;border-radius:6px;padding:5px 10px;" autofocus>\';',
'                            h += \'<button onclick="amArSaveEdit(this)" data-aid="\' + a.id + \'" style="border:none;background:#E8F5E9;color:#2E7D32;padding:5px 10px;border-radius:6px;cursor:pointer;font-size:.78rem;font-weight:600;"><i class="fas fa-check" style="margin-right:3px;"></i>Save</button>\';',
'                            h += \'<button onclick="amArCancelEdit()" style="border:none;background:#eee;color:#555;padding:5px 10px;border-radius:6px;cursor:pointer;font-size:.78rem;"><i class="fas fa-times"></i></button>\';',
'                        } else {',
'                            h += \'<i class="fas fa-map" style="color:#9C27B0;font-size:.8rem;"></i>\';',
'                            h += \'<span style="flex:1;font-weight:600;font-size:.87rem;color:#4A148C;">\' + a.name + \'</span>\';',
'                            h += \'<span style="font-size:.72rem;color:#aaa;margin-right:4px;">linked to \' + lmName + \'</span>\';',
'                            h += \'<button onclick="amArStartEdit(this)" data-aid="\' + a.id + \'" style="border:none;background:#EDE7F6;color:#6A1B9A;padding:5px 10px;border-radius:6px;cursor:pointer;font-size:.78rem;font-weight:600;" title="Edit/Rename"><i class="fas fa-pen" style="margin-right:3px;"></i>Edit</button>\';',
'                            h += \'<button onclick="amArDelete(this)" data-aid="\' + a.id + \'" style="border:none;background:#FFEBEE;color:#c0392b;padding:5px 10px;border-radius:6px;cursor:pointer;font-size:.78rem;" title="Delete"><i class="fas fa-trash"></i></button>\';',
'                        }',
'                        h += \'</div>\';',
'                    });',
'                }',
'                h += \'</div>\';', // end areas list
'            }',
'',
'            h += \'</div>\';', // end right col
'            h += \'</div>\';', // end grid
'',
'            // Footer note',
'            h += \'<div style="margin-top:16px;padding-top:12px;border-top:1px solid #f0f0f0;display:flex;justify-content:space-between;align-items:center;">\';',
'            h += \'<span style="font-size:.73rem;color:#aaa;"><i class="fas fa-link" style="margin-right:4px;"></i>Areas are automatically available in the volunteer donation form when their Landmark is selected.</span>\';',
'            h += \'<button onclick="document.getElementById(\\\'adeAreasMgrModal\\\').remove();adeLandmarkModal();" style="padding:6px 14px;border:none;border-radius:8px;background:#FFF3E0;color:#E65100;font-weight:700;cursor:pointer;font-size:.78rem;"><i class="fas fa-map-marker-alt" style="margin-right:5px;"></i>Manage Landmarks</button>\';',
'            h += \'</div>\';',
'',
'            h += \'</div>\';', // end card
'            overlay.innerHTML = h;',
'        }',
'',
'        // ── Actions ──────────────────────────────────────────────────────────',
'        window.amArSelLm = function(el) { selLmId = el.dataset.lid; editingAr = null; render(); };',
'',
'        window.amArAddArea = async function(btn) {',
'            var lmid = btn.dataset.lmid;',
'            var name = ((document.getElementById(\'amArNewInput\')||{}).value||\'\').trim();',
'            if (!name) { alert(\'Please enter an area name.\'); return; }',
'            var r = await fetch(\'/api/areas\', { method:\'POST\', headers:{\'Content-Type\':\'application/json\'}, body:JSON.stringify({ name: name, landmarkId: lmid }) });',
'            var d = await r.json();',
'            if (r.ok && d.success) {',
'                allAreas.push(d.area);',
'                _adeAllAreas = allAreas;',
'                await adeLoadDropdownsIfNeeded();',
'                editingAr = null;',
'                render();',
'            } else { alert(d.message || \'Could not add area.\'); }',
'        };',
'',
'        window.amArStartEdit = function(btn) { editingAr = btn.dataset.aid; render(); setTimeout(function(){ var inp = document.getElementById(\'amArEditInput_\' + editingAr); if (inp) { inp.focus(); inp.select(); } }, 40); };',
'        window.amArCancelEdit = function() { editingAr = null; render(); };',
'',
'        window.amArSaveEdit = async function(btn) {',
'            var id  = btn.dataset.aid;',
'            var inp = document.getElementById(\'amArEditInput_\' + id);',
'            var nm  = inp ? inp.value.trim() : \'\';',
'            if (!nm) { alert(\'Area name cannot be empty.\'); return; }',
'            var r = await fetch(\'/api/areas/\'+encodeURIComponent(id), { method:\'PUT\', headers:{\'Content-Type\':\'application/json\'}, body:JSON.stringify({ name: nm }) });',
'            var d = await r.json();',
'            if (r.ok && d.success) {',
'                var i = allAreas.findIndex(function(a){return a.id===id;});',
'                if (i >= 0) allAreas[i].name = nm;',
'                _adeAllAreas = allAreas;',
'                await adeLoadDropdownsIfNeeded();',
'                editingAr = null;',
'                render();',
'            } else { alert(d.message || \'Rename failed.\'); }',
'        };',
'',
'        window.amArDelete = async function(btn) {',
'            var id = btn.dataset.aid;',
'            if (!confirm(\'Delete this area? This cannot be undone.\')) return;',
'            var r = await fetch(\'/api/areas/\'+encodeURIComponent(id), { method:\'DELETE\' });',
'            if (r.ok) {',
'                allAreas = allAreas.filter(function(a){return a.id!==id;});',
'                _adeAllAreas = allAreas;',
'                await adeLoadDropdownsIfNeeded();',
'                editingAr = null;',
'                render();',
'            } else { alert(\'Could not delete area.\'); }',
'        };',
'',
'        // Helper: reload the form dropdowns so changes are reflected immediately',
'        async function adeLoadDropdownsIfNeeded() {',
'            if (typeof adeLoadAreas === \'function\') {',
'                var lm = allLandmarks.find(function(l){return l.id===selLmId;});',
'                if (lm) await adeLoadAreas(lm.name);',
'            }',
'        }',
'',
'        render();',
'        document.body.appendChild(overlay);',
'        overlay.addEventListener(\'click\', function(ev) { if (ev.target === overlay) overlay.remove(); });',
'    }'
].join('\r\n');

const OLD_CRLF = OLD.replace(/\n/g, '\r\n');
if (html.includes(OLD_CRLF)) {
    html = html.replace(OLD_CRLF, NEW.replace(/\n/g, '\r\n'));
    console.log('PATCH: adeManageAreasModal replaced (CRLF)');
} else if (html.includes(OLD)) {
    html = html.replace(OLD, NEW);
    console.log('PATCH: adeManageAreasModal replaced (LF)');
} else {
    console.error('PATCH: OLD string NOT FOUND');
    process.exit(1);
}

fs.writeFileSync('admin.html', html);
console.log('Done.');
